# Generated by Django 5.2.14 on 2026-07-31 08:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JiraConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('base_url', models.URLField(max_length=512)),
                ('email', models.EmailField(max_length=254)),
                ('api_token_encrypted', models.TextField()),
                ('project_key', models.CharField(max_length=64)),
                ('board_id', models.CharField(blank=True, default='', max_length=64)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('last_test_at', models.DateTimeField(blank=True, null=True)),
                ('last_test_status', models.CharField(choices=[('unknown', 'Unknown'), ('success', 'Success'), ('failed', 'Failed')], default='unknown', max_length=16)),
                ('last_test_error', models.CharField(blank=True, default='', max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_jira_connections', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jira_connections', to='tenants.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['workspace', 'is_active'], name='jira_jiraco_workspa_55b3e2_idx')],
                'constraints': [models.UniqueConstraint(fields=('workspace', 'name'), name='unique_jira_connection_name_per_workspace')],
            },
        ),
    ]
