# Generated by Django 5.2.16 on 2026-07-31 11:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jira', '0002_metadata_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='JiraGuide',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=128, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.CharField(blank=True, default='', max_length=512)),
                ('locale', models.CharField(default='ru', max_length=16)),
                ('content', models.JSONField(blank=True, default=list)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['slug'],
                'indexes': [models.Index(fields=['is_published'], name='jira_jiragu_is_publ_c06de4_idx')],
            },
        ),
    ]
