"""Shared OpenAPI components: errors, headers, security."""
from drf_spectacular.utils import OpenApiExample, OpenApiParameter, OpenApiResponse, inline_serializer
from rest_framework import serializers

TRACE_ID_HEADER = OpenApiParameter(
    name="X-Trace-Id",
    type=str,
    location=OpenApiParameter.HEADER,
    required=False,
    description=(
        "Optional correlation id for request tracing. "
        "If omitted, the server generates one and returns it in the response header."
    ),
)

WORKSPACE_ID_PATH = OpenApiParameter(
    name="id",
    type=str,
    location=OpenApiParameter.PATH,
    description="Workspace UUID. Non-members receive 404 NOT_FOUND (not 403).",
)

ApiErrorSerializer = inline_serializer(
    name="ApiError",
    fields={
        "traceId": serializers.CharField(
            help_text="Request trace id (from X-Trace-Id or generated by middleware).",
        ),
        "code": serializers.CharField(
            help_text="Machine-readable error code, e.g. VALIDATION_ERROR, NOT_FOUND.",
        ),
        "message": serializers.CharField(help_text="Human-readable error summary."),
        "fieldErrors": serializers.DictField(
            child=serializers.ListField(child=serializers.CharField()),
            help_text="Per-field validation errors; empty object for non-field errors.",
        ),
    },
)

VALIDATION_ERROR_EXAMPLE = OpenApiExample(
    name="Validation error",
    value={
        "traceId": "550e8400-e29b-41d4-a716-446655440000",
        "code": "VALIDATION_ERROR",
        "message": "Invalid input.",
        "fieldErrors": {"name": ["This field is required."]},
    },
    response_only=True,
)

UNAUTHORIZED_EXAMPLE = OpenApiExample(
    name="Missing JWT",
    value={
        "traceId": "550e8400-e29b-41d4-a716-446655440000",
        "code": "UNAUTHORIZED",
        "message": "Authentication credentials were not provided.",
        "fieldErrors": {},
    },
    response_only=True,
)

NOT_FOUND_EXAMPLE = OpenApiExample(
    name="Not found",
    value={
        "traceId": "550e8400-e29b-41d4-a716-446655440000",
        "code": "NOT_FOUND",
        "message": "Workspace not found.",
        "fieldErrors": {},
    },
    response_only=True,
)

FORBIDDEN_EXAMPLE = OpenApiExample(
    name="Forbidden",
    value={
        "traceId": "550e8400-e29b-41d4-a716-446655440000",
        "code": "FORBIDDEN",
        "message": "You do not have permission to perform this action.",
        "fieldErrors": {},
    },
    response_only=True,
)


def error_response(
    status_code: int,
    description: str,
    *,
    examples: list[OpenApiExample] | None = None,
) -> OpenApiResponse:
    return OpenApiResponse(
        response=ApiErrorSerializer,
        description=description,
        examples=examples or [],
    )


API_ERROR_400 = error_response(
    400,
    "Invalid input or business rule violation (`VALIDATION_ERROR`, `TOKEN_INVALID`, `TOKEN_EXPIRED`).",
    examples=[VALIDATION_ERROR_EXAMPLE],
)
API_ERROR_401 = error_response(
    401,
    "Missing or invalid JWT (`UNAUTHORIZED`, `INVALID_CREDENTIALS`, `AUTHENTICATION_FAILED`).",
    examples=[UNAUTHORIZED_EXAMPLE],
)
API_ERROR_403 = error_response(
    403,
    "Authenticated but not allowed (`FORBIDDEN`, `EMAIL_NOT_VERIFIED`).",
    examples=[FORBIDDEN_EXAMPLE],
)
API_ERROR_404 = error_response(
    404,
    "Resource not found or hidden from non-members (`NOT_FOUND`).",
    examples=[NOT_FOUND_EXAMPLE],
)

AUTHENTICATED_ERRORS = {
    400: API_ERROR_400,
    401: API_ERROR_401,
    403: API_ERROR_403,
    404: API_ERROR_404,
}

PUBLIC_ERRORS = {
    400: API_ERROR_400,
}

MessageResponseSerializer = inline_serializer(
    name="MessageResponse",
    fields={
        "message": serializers.CharField(help_text="Operation result message."),
    },
)

MESSAGE_RESPONSE = MessageResponseSerializer
