# Generated by Django 5.2.14 on 2026-05-29 23:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trace_id', models.CharField(db_index=True, max_length=64)),
                ('action', models.CharField(db_index=True, max_length=128)),
                ('entity_type', models.CharField(db_index=True, max_length=64)),
                ('entity_id', models.CharField(blank=True, default='', max_length=128)),
                ('payload_snapshot', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['entity_type', 'entity_id'], name='audit_audit_entity__9535bf_idx')],
            },
        ),
    ]
