"""Shared validation constants for jira app."""
MIN_CONNECTION_NAME_LENGTH = 1
MAX_CONNECTION_NAME_LENGTH = 255
MAX_PROJECT_KEY_LENGTH = 64
MAX_BOARD_ID_LENGTH = 64
MAX_BASE_URL_LENGTH = 512

PROJECT_KEY_PATTERN = r"^[A-Z][A-Z0-9_]*$"

JIRA_MYSELF_PATH = "/rest/api/3/myself"
JIRA_REQUEST_TIMEOUT_SECONDS = 15.0
JIRA_TEST_MAX_RETRIES = 3
