# Generated by Django 5.2.16 on 2026-08-03 09:32

import django.db.models.deletion
import sources.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to=sources.models.source_file_upload_path)),
                ('file_type', models.CharField(choices=[('xlsx', 'Excel (.xlsx)'), ('csv', 'CSV')], max_length=8)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('content_type', models.CharField(blank=True, default='', max_length=128)),
                ('checksum', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('parsing', 'Parsing'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('encoding', models.CharField(blank=True, default='', max_length=32)),
                ('delimiter', models.CharField(blank=True, default='', max_length=8)),
                ('sheet_count', models.PositiveIntegerField(default=0)),
                ('error_message', models.CharField(blank=True, default='', max_length=2000)),
                ('parse_started_at', models.DateTimeField(blank=True, null=True)),
                ('parsed_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_source_files', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_files', to='tenants.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SourceSheet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('index', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('column_count', models.PositiveIntegerField(default=0)),
                ('columns', models.JSONField(blank=True, default=list)),
                ('preview_rows', models.JSONField(blank=True, default=list)),
                ('source_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sheets', to='sources.sourcefile')),
            ],
            options={
                'ordering': ['index'],
            },
        ),
        migrations.AddIndex(
            model_name='sourcefile',
            index=models.Index(fields=['workspace', 'is_active'], name='sources_sou_workspa_b849b2_idx'),
        ),
        migrations.AddIndex(
            model_name='sourcefile',
            index=models.Index(fields=['workspace', 'status'], name='sources_sou_workspa_d3a088_idx'),
        ),
        migrations.AddIndex(
            model_name='sourcesheet',
            index=models.Index(fields=['source_file'], name='sources_sou_source__d8d119_idx'),
        ),
        migrations.AddConstraint(
            model_name='sourcesheet',
            constraint=models.UniqueConstraint(fields=('source_file', 'index'), name='unique_source_sheet_index_per_file'),
        ),
    ]
