# Generated by Django 5.2.16 on 2026-08-03 10:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleSheetSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('spreadsheet_id', models.CharField(max_length=128)),
                ('spreadsheet_url', models.URLField(blank=True, default='', max_length=512)),
                ('worksheet_title', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('parsing', 'Parsing'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('sheet_count', models.PositiveIntegerField(default=0)),
                ('error_message', models.CharField(blank=True, default='', max_length=2000)),
                ('last_sync_started_at', models.DateTimeField(blank=True, null=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_google_sheet_sources', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='google_sheet_sources', to='tenants.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GoogleSheetTab',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('index', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('column_count', models.PositiveIntegerField(default=0)),
                ('columns', models.JSONField(blank=True, default=list)),
                ('preview_rows', models.JSONField(blank=True, default=list)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tabs', to='sources.googlesheetsource')),
            ],
            options={
                'ordering': ['index'],
            },
        ),
        migrations.AddIndex(
            model_name='googlesheetsource',
            index=models.Index(fields=['workspace', 'is_active'], name='sources_goo_workspa_ccca3e_idx'),
        ),
        migrations.AddIndex(
            model_name='googlesheetsource',
            index=models.Index(fields=['workspace', 'status'], name='sources_goo_workspa_1da2d5_idx'),
        ),
        migrations.AddIndex(
            model_name='googlesheettab',
            index=models.Index(fields=['source'], name='sources_goo_source__ae5405_idx'),
        ),
        migrations.AddConstraint(
            model_name='googlesheettab',
            constraint=models.UniqueConstraint(fields=('source', 'index'), name='unique_google_sheet_tab_index_per_source'),
        ),
    ]
