# Generated by Django 5.2.16 on 2026-08-09 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0006_snapshot_cleanup_periodic'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='presetbinding',
            new_name='sources_pre_workspa_4b2d52_idx',
            old_name='sources_pre_workspa_preset_idx',
        ),
        migrations.RenameIndex(
            model_name='presetbinding',
            new_name='sources_pre_workspa_2728d8_idx',
            old_name='sources_pre_workspa_applied_idx',
        ),
        migrations.RenameIndex(
            model_name='sourcepreset',
            new_name='sources_sou_workspa_784fb7_idx',
            old_name='sources_sou_workspa_idx',
        ),
        migrations.RenameIndex(
            model_name='sourcepreset',
            new_name='sources_sou_workspa_67c5f2_idx',
            old_name='sources_sou_workspa_type_idx',
        ),
        migrations.RenameIndex(
            model_name='sourcerefreshrun',
            new_name='sources_sou_workspa_dce15e_idx',
            old_name='sources_ref_workspa_hist_idx',
        ),
        migrations.RenameIndex(
            model_name='sourcerefreshrun',
            new_name='sources_sou_snapsho_312d6e_idx',
            old_name='sources_ref_snapsho_idx',
        ),
        migrations.RenameIndex(
            model_name='sourcesnapshot',
            new_name='sources_sou_workspa_83fa83_idx',
            old_name='sources_sou_workspa_snap_idx',
        ),
        migrations.RenameIndex(
            model_name='sourcesnapshot',
            new_name='sources_sou_source__8fea49_idx',
            old_name='sources_sou_type_id_act_idx',
        ),
        migrations.RenameIndex(
            model_name='sourcesnapshot',
            new_name='sources_sou_created_0ae8a9_idx',
            old_name='sources_sou_created_snap_idx',
        ),
    ]
